export const RSWETH_ABI = [
	{
		"inputs": [],
		"name": "getRate",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "rswETHToETHRate",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "deposit",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	}
];



const FULL_RSWETH_ABI = [
    {
       "inputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"AddressAlreadyInWhitelist",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"AddressMissingFromWhitelist",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"CannotBeZeroAddress",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"CannotBurnZeroRswETH",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"CannotReferSelf",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"CannotRepriceWithZeroRswETHSupply",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"CoreMethodsPaused",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"rswETHAmount",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"minRswETH",
             "type":"uint256"
          }
       ],
       "name":"InsufficientRswETHReceived",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"InvalidETHDeposit",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"InvalidMethodCall",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"InvalidPreRewardETHReserves",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"NoTokensToWithdraw",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"remainingTime",
             "type":"uint256"
          }
       ],
       "name":"NotEnoughTimeElapsedForReprice",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"NotInWhitelist",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OnlyDepositManager",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"x",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"y",
             "type":"uint256"
          }
       ],
       "name":"PRBMath_MulDiv18_Overflow",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"x",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"y",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"denominator",
             "type":"uint256"
          }
       ],
       "name":"PRBMath_MulDiv_Overflow",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"repriceDiff",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"maximumRepriceDiff",
             "type":"uint256"
          }
       ],
       "name":"RepriceDifferenceTooLarge",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"repriceRswETHDiff",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"maximumRswETHRepriceDiff",
             "type":"uint256"
          }
       ],
       "name":"RepriceRswETHDifferenceTooLarge",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"RewardPercentageTotalOverflow",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"WhitelistAlreadyDisabled",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"WhitelistAlreadyEnabled",
       "type":"error"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"AddedToWhitelist",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"Approval",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"_receiver",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_ethSpent",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_rswETHReceived",
             "type":"uint256"
          }
       ],
       "name":"DepoistManagerDeposit",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"rswETHMinted",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newTotalETHDeposited",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"referral",
             "type":"address"
          }
       ],
       "name":"ETHDepositReceived",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"rswETHBurned",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"ethReturned",
             "type":"uint256"
          }
       ],
       "name":"ETHWithdrawn",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint8",
             "name":"version",
             "type":"uint8"
          }
       ],
       "name":"Initialized",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_oldMaximumRepriceDifferencePercentage",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_newMaximumRepriceDifferencePercentage",
             "type":"uint256"
          }
       ],
       "name":"MaximumRepriceDifferencePercentageUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_oldMaximumRepriceRswETHDifferencePercentage",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_newMaximumRepriceRswETHDifferencePercentage",
             "type":"uint256"
          }
       ],
       "name":"MaximumRepriceRswETHDifferencePercentageUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_oldMinimumRepriceTime",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_newMinimumRepriceTime",
             "type":"uint256"
          }
       ],
       "name":"MinimumRepriceTimeUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"oldPercentage",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newPercentage",
             "type":"uint256"
          }
       ],
       "name":"NodeOperatorRewardPercentageUpdate",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"RemovedFromWhitelist",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newEthReserves",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newRswETHToETHRate",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"nodeOperatorRewards",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"swellTreasuryRewards",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"totalETHDeposited",
             "type":"uint256"
          }
       ],
       "name":"Reprice",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"oldPercentage",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newPercentage",
             "type":"uint256"
          }
       ],
       "name":"SwellTreasuryRewardPercentageUpdate",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"Transfer",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          
       ],
       "name":"WhitelistDisabled",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          
       ],
       "name":"WhitelistEnabled",
       "type":"event"
    },
    {
       "stateMutability":"nonpayable",
       "type":"fallback"
    },
    {
       "inputs":[
          
       ],
       "name":"AccessControlManager",
       "outputs":[
          {
             "internalType":"contract IAccessControlManager",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"addToWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          }
       ],
       "name":"allowance",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"approve",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"balanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address[]",
             "name":"_addresses",
             "type":"address[]"
          }
       ],
       "name":"batchAddToWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address[]",
             "name":"_addresses",
             "type":"address[]"
          }
       ],
       "name":"batchRemoveFromWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"burn",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"decimals",
       "outputs":[
          {
             "internalType":"uint8",
             "name":"",
             "type":"uint8"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"subtractedValue",
             "type":"uint256"
          }
       ],
       "name":"decreaseAllowance",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"deposit",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"_to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_minRswETH",
             "type":"uint256"
          }
       ],
       "name":"depositViaDepositManager",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"referral",
             "type":"address"
          }
       ],
       "name":"depositWithReferral",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"disableWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"enableWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"ethToRswETHRate",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getRate",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"addedValue",
             "type":"uint256"
          }
       ],
       "name":"increaseAllowance",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"contract IAccessControlManager",
             "name":"_accessControlManager",
             "type":"address"
          }
       ],
       "name":"initialize",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"lastRepriceETHReserves",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"lastRepriceUNIX",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"maximumRepriceDifferencePercentage",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"maximumRepriceRswETHDifferencePercentage",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"minimumRepriceTime",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"name",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"nodeOperatorRewardPercentage",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_address",
             "type":"address"
          }
       ],
       "name":"removeFromWhitelist",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_preRewardETHReserves",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_newETHRewards",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_rswETHTotalSupply",
             "type":"uint256"
          }
       ],
       "name":"reprice",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"rswETHToETHRate",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_maximumRepriceDifferencePercentage",
             "type":"uint256"
          }
       ],
       "name":"setMaximumRepriceDifferencePercentage",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_maximumRepriceRswETHDifferencePercentage",
             "type":"uint256"
          }
       ],
       "name":"setMaximumRepriceRswETHDifferencePercentage",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_minimumRepriceTime",
             "type":"uint256"
          }
       ],
       "name":"setMinimumRepriceTime",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_newNodeOperatorRewardPercentage",
             "type":"uint256"
          }
       ],
       "name":"setNodeOperatorRewardPercentage",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_newSwellTreasuryRewardPercentage",
             "type":"uint256"
          }
       ],
       "name":"setSwellTreasuryRewardPercentage",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"swellTreasuryRewardPercentage",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"symbol",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"totalETHDeposited",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"totalSupply",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"transfer",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"transferFrom",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"whitelistEnabled",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"whitelistedAddresses",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"contract IERC20",
             "name":"_token",
             "type":"address"
          }
       ],
       "name":"withdrawERC20",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]



export const STAKING_ABI = [
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_nativeTokenWrapper",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         
      ],
      "name":"ContractMetadataUnauthorized",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"expected",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"actual",
            "type":"uint256"
         }
      ],
      "name":"CurrencyTransferLibMismatchedValue",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         }
      ],
      "name":"PermissionsAlreadyGranted",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"expected",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"actual",
            "type":"address"
         }
      ],
      "name":"PermissionsInvalidPermission",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"bytes32",
            "name":"neededRole",
            "type":"bytes32"
         }
      ],
      "name":"PermissionsUnauthorizedAccount",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"string",
            "name":"prevURI",
            "type":"string"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"newURI",
            "type":"string"
         }
      ],
      "name":"ContractURIUpdated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"version",
            "type":"uint8"
         }
      ],
      "name":"Initialized",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"RewardTokensDepositedByAdmin",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"RewardTokensWithdrawnByAdmin",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"staker",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"rewardAmount",
            "type":"uint256"
         }
      ],
      "name":"RewardsClaimed",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"previousAdminRole",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"newAdminRole",
            "type":"bytes32"
         }
      ],
      "name":"RoleAdminChanged",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         }
      ],
      "name":"RoleGranted",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         }
      ],
      "name":"RoleRevoked",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"staker",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"TokensStaked",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"staker",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"TokensWithdrawn",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"oldAmount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"newAmount",
            "type":"uint256"
         }
      ],
      "name":"UpdatedMinStakeAmount",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"oldNumerator",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"newNumerator",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"oldDenominator",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"newDenominator",
            "type":"uint256"
         }
      ],
      "name":"UpdatedRewardRatio",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"oldTimeUnit",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"newTimeUnit",
            "type":"uint256"
         }
      ],
      "name":"UpdatedTimeUnit",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"DEFAULT_ADMIN_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"claimRewards",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"contractType",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"contractURI",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"contractVersion",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"depositRewardTokens",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getRewardRatio",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"_numerator",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_denominator",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getRewardTokenBalance",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         }
      ],
      "name":"getRoleAdmin",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"uint256",
            "name":"index",
            "type":"uint256"
         }
      ],
      "name":"getRoleMember",
      "outputs":[
         {
            "internalType":"address",
            "name":"member",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         }
      ],
      "name":"getRoleMemberCount",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"count",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_staker",
            "type":"address"
         }
      ],
      "name":"getStakeInfo",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"_tokensStaked",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_rewards",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getTimeUnit",
      "outputs":[
         {
            "internalType":"uint80",
            "name":"_timeUnit",
            "type":"uint80"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"grantRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"hasRole",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"hasRoleWithSwitch",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_defaultAdmin",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"_contractURI",
            "type":"string"
         },
         {
            "internalType":"address[]",
            "name":"_trustedForwarders",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"_rewardToken",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_stakingToken",
            "type":"address"
         },
         {
            "internalType":"uint80",
            "name":"_timeUnit",
            "type":"uint80"
         },
         {
            "internalType":"uint256",
            "name":"_rewardRatioNumerator",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_rewardRatioDenominator",
            "type":"uint256"
         }
      ],
      "name":"initialize",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"forwarder",
            "type":"address"
         }
      ],
      "name":"isTrustedForwarder",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes[]",
            "name":"data",
            "type":"bytes[]"
         }
      ],
      "name":"multicall",
      "outputs":[
         {
            "internalType":"bytes[]",
            "name":"results",
            "type":"bytes[]"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"renounceRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"role",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"revokeRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"rewardToken",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"rewardTokenDecimals",
      "outputs":[
         {
            "internalType":"uint16",
            "name":"",
            "type":"uint16"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"string",
            "name":"_uri",
            "type":"string"
         }
      ],
      "name":"setContractURI",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_numerator",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_denominator",
            "type":"uint256"
         }
      ],
      "name":"setRewardRatio",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint80",
            "name":"_timeUnit",
            "type":"uint80"
         }
      ],
      "name":"setTimeUnit",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"stake",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"stakers",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"timeOfLastUpdate",
            "type":"uint128"
         },
         {
            "internalType":"uint64",
            "name":"conditionIdOflastUpdate",
            "type":"uint64"
         },
         {
            "internalType":"uint256",
            "name":"amountStaked",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"unclaimedRewards",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"stakersArray",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"stakingToken",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"stakingTokenBalance",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"stakingTokenDecimals",
      "outputs":[
         {
            "internalType":"uint16",
            "name":"",
            "type":"uint16"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"withdraw",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"withdrawRewardTokens",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "stateMutability":"payable",
      "type":"receive"
   }
]